### ISSUE TITLE
Timer only updates based on difficulty on new window

### ISSUE THREAD

**Issue by jgetzel** [cse210-fa24-group5/cse210-fa24-group5#48]
**Describe the bug**
Time does not update its difficulty when accessing a problem from within the same window

**To Reproduce**
1. Go to problem
2. Click on problem from the same page with a different difficulty
3. See the timer is not updated

**Expected behavior**
Timer updates properly based on the new problems difficulty

**Comment by JackLiX0105** [comment]
Solved in 1333d1d
